name: Publish Python distributions to PyPI
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: install deployment dependancies
        if: github.event.pull_request.merged == true
        run: |
          pip install twine
          pip install pexpect
      - name: package module
        if: github.event.pull_request.merged == true
        run: python setup.py sdist
      - name: deploy to pypi
        if: github.event.pull_request.merged == true
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD}}
        run: |
          twine upload dist/*
  try-install:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: python3.8
      - name: Install Package
        run: pip install random-regex