name: Run tests
on: 
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: run type checking
        run: | 
         pip install mypy
         pip install types-requests
         mypy random_regex --ignore-missing-imports
      - name: flake8 checking
        run: |
         pip install flake8
         flake8 --ignore=E501,W504
      - name: run tests
        run: | 
          pip install -r requirements-test.txt
          pytest
      - name: check version
        run: |
          pip install requests
          python .github/check_version.py