name: Run tests
on: 
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: run type checking
        run: | 
         pip install mypy
         pip install types-requests
         mypy regex_generator --ignore-missing-imports
      - name: flake8 checking
        run: |
         pip install flake8
         flake8 --ignore=E501,W504
      - name: run tests
        run: | 
          pip install pytest
          pytest
        env: 
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: check version
        run: |
          pip install requests
          python .github/check_version.py